### ISSUE TITLE
Not showing in Addins, Fix isn't working

### ISSUE THREAD

**Issue by SheiFoxy** [draconas1/masterplan-json-export#12]
I'm not getting the tool showing up. I installed the loose files to the root and Addins folders. 
I have nothing relevant in the logs as I can tell because they haven't updated since I installed this Addin. 

The logs include :
`8/19/2022 2:41:52 AM	Object reference not set to an instance of an object.
8/19/2022 2:41:52 AM	   at System.Windows.Forms.ToolStripControlHost.get_Text()
   at Masterplan.UI.MainForm.Application_Idle(Object sender, EventArgs e)
`

and
`8/17/2022 4:18:37 PM	Object reference not set to an instance of an object.
8/17/2022 4:18:37 PM	   at Masterplan.Controls.PlotView.allow_drop(PlotPoint dragged, Point pt)
`

But that was from days ago so I don't think it's related to this?

Using Masterplan 12.2 found here: https://github.com/andyaiken/masterplan/releases/tag/v12.2
Using your exporter found here: https://github.com/draconas1/masterplan-json-export

Any help?

**Comment by draconas1** [comment]
That error does not look related. 

If you have the loose files in both locations and are not getting the package error, then I have no idea.  I don't used MP 12 due to the issues with addins.

**Comment by SheiFoxy** [comment]
Which version should I use and where could I find the version you recommend?

**Comment by draconas1** [comment]
Then I don't know what is going on.  I double checked by installing the latest release files in my version Masterplan (11.9) and it works fine.    

I've included the zipped directory for you to drop into the Masterplan directory.  I'm afraid if this doesn't work you will need to get support from Masterplans authors directly on the dnd4e discord server if they are still about and answering questions.  

[AddIns.zip](https://github.com/draconas1/masterplan-json-export/files/9432009/AddIns.zip)

**Comment by SheiFoxy** [comment]
This worked! with version 12.2 even.
But these files are different than the ones I downloaded from the main page for your addin.
On this page: https://github.com/draconas1/masterplan-json-export
I clicked Code>Download Zip 
And that was the set of files I put in my Addins/Root.

Those are different from the ones you just sent me.

Did I download it wrong?

**Comment by draconas1** [comment]
Yes, you downloaded the source code not the binary files, git adds the sourcecode itself so I can't get rid of them.  I will update the instructions to make it more clear.
