### ISSUE TITLE
Scripts won't run on Roll20, reporting an error in syntax.

### ISSUE THREAD

**Issue by SheiFoxy** [draconas1/masterplan-json-export#13]
When I copy the scripts into Roll20, I get the following:
https://i.gyazo.com/0601d7fcbe2a4b4fdd3dccef96738e0d.png

I get it if I enable any one of the four scripts.

**Comment by draconas1** [comment]
So I suspect that something has gone wrong with copying and pasting, can you do me a screenshot of what the script looks like please?

So directly copying from github may have picked up some unwelcome formatting.  What i suggest you do is create 4 new scripts in Roll20 (delete any you have previously created), name them appropriately based on my files.  Then for the 4 .js files in the Roll20Api folder in git, open the file and on the top right of the file display click the `raw` button, that will open the text file itself, no fancy formatting, copy the contents of that and paste it into the relevant roll 20 script.

**Comment by SheiFoxy** [comment]
Copying the raw worked! Thank you so much!

**Comment by draconas1** [comment]
I will update the documentation.
